version: '3.9'

services:
  client:
      container_name: client
      build:
        context: .
        dockerfile: Dockerfile.client
      ports:
        - "4200:4200"
      environment:
        - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      depends_on:
        - api
      entrypoint: ["sh", "-c", "sleep 10 && npx nx run client:dev -p 4200"]

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_PORT=5432
    depends_on:
      - db
  db: 
    container_name: db
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
